name: build and test

env:
    REQUIREMENTS_PATH: './backend/requirements.txt'

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Codecov
              uses: codecov/codecov-action@v5.0.2

             # Step 2: Debug directory structure
            - name: Debug file structure
              run: |
                echo "Listing all files in the repository:"
                ls -R

            # Step 3: Verify requirements file exists
            - name: Verify requirements file exists
              run: |
                if [ ! -f "$REQUIREMENTS_PATH" ]; then
                echo "Error: $REQUIREMENTS_PATH not found!"
                exit 1
                fi

            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: "3.x"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r $REQUIREMENTS_PATH

            - name: Build complete
              run: echo "all steps complete"